CREATE TABLE IF NOT EXISTS Payload (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deveui TEXT NOT NULL,
    payload TEXT NOT NULL,
    ts REAL NOT NULL,
    FOREIGN KEY(deveui) REFERENCES Device(deveui)
);

CREATE TABLE IF NOT EXISTS Profile (
    pid INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    decoder TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Device (
    deveui TEXT PRIMARY KEY,
    pid INTEGER NOT NULL,
    FOREIGN KEY(pid) REFERENCES Profile(pid)
)WITHOUT ROWID;